### ISSUE TITLE
Make 'httpx' optional requirement

### ISSUE THREAD

**Issue by rudyryk** [malinkinsa/asyncgelf#11]
**Is your feature request related to a problem? Please describe.**
For lightweight setups we'd want to minimize dependencies. Technically 'httpx' is only required for HTTP handler but not for TCP and UDP. 

**Describe the solution you'd like**
Wrap 'httpx' import into `try..except` and remove from required dependencies.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by malinkinsa** [comment]
Hello.
It looks like a breaking change for all who use the http handler. It would be possible to add an automatic installation to the condition of the error, but I don’t really like this option. At this moment i can't make a http part on clean stdlib.
