### ISSUE TITLE
Possible blocking operation in GelfUdp

### ISSUE THREAD

**Issue by rudyryk** [malinkinsa/asyncgelf#12]
**Describe the bug**
(https://github.com/malinkinsa/asyncgelf/blob/8054a37ef3f12fbcc4003ceef7cbda64c2ab5c2a/asyncgelf/asyncgelf.py#L262)

in the line above sync call from async happens.

**To Reproduce**

Minimal code example:

```python
import asyncio
import asyncgelf
handler = asyncgelf.GelfUdp(host='127.0.0.1')
asyncio.run(handler.udp_handler({'text': 'yo!'}))
```

**Expected behavior**
Actually I think that it's also extremely useful to have both sync and async interfaces. So the expected behaviour is sync calls to happen synchronously and async to happen asynchronously.

**Additional context**
So the current implementation for GelfUdp from what I can see is pretty much sync, and the `GelfUdp.make_gelf_chunks()` is sync as well.

**Comment by malinkinsa** [comment]
> in the line above sync call from async happens.

It is a non blocking call.

About `make_gelf_chunks()` - this block works inside coroutine and and applies only to part of the input data.

In my tests i read multiline files line by line and send them in to graylog. I see they come in a different order
